Add dual stack support
flannel-io/flannel pull request #1398
Opened 2021-01-15 11:21 UTC by yaoice

Add dual stack support for flannel, it provided with theree mode for flannel:
1. Only ipv4 stack as the origin.
2. Only ipv6 stack
3. Dual stack 

Add new option for flannel daemon to support dual stack:
- "publicIPv6": "IPv6 accessible by other nodes for
  inter-host communication"
- "auto-detect-ipv4": "auto detect ipv4 address of the iface",
  default value is true.
- "auto-detect-ipv6": "auto detect ipv6 address of the iface",
  default value is false

Add new option into `net-conf.json` configuration, like following:
```
{
  "EnableIPv4": true,
  "EnableIPv6": true,
  "Network": "172.16.0.0/16",
  "IPv6Network": "fc00::/48",
  "Backend": {
    "Type": "vxlan"
  }
}
```
`EnableIPv4` default value is true for useing kube subnet manager.
`EnableIpv6` default value is false.

Flannel dual stack feature has limitation, only work with vxlan backend
and kube subnet manager now. To enable flannel dual stack feature, need
to do the following step:
1. setting flanneld daemon with `--kube-subnet-mgr --auto-detect-ipv6`
2. settting `EnableIPv6` and `IPv6Network` in `net-conf.json`, like the
    above configuration.
3. setting network interface that flannel used ipv6 address and
default ipv6 gateway in the host node.
4. vxlan support ipv6 tunnel require kernel version >= 3.12.

It also need flannel cni plugin to support dual stack ip allocation, so it 
depends on: [https://github.com/containernetworking/plugins/pull/570](https://github.com/containernetworking/plugins/pull/570 )

#248

Signed-off-by: yaoice <yao3690093@gmail.com>

2021-01-18 02:39 UTC, yaoice commented
@rajatchopra

2021-01-21 16:54 UTC, luthermonson commented
this looks like a good one for v0.14.x after we finish up RCs for 13 and get v0.13.1 out. probably can merge this pretty quick and RC it for testing purposes.

2021-03-31 11:10 UTC, unixfox commented
Hello @luthermonson,
Any news about the time when you plan to start working on v0.14.x RC versions?
Kubernetes 1.21 is going to be soon released with dual stack support in beta and I would like to use flannel on a dual stack Kubernetes 1.21 cluster.
K3s is considering to add dual stack support, but it is blocked (https://github.com/k3s-io/k3s/pull/3049#issuecomment-797383621) by this pull request because flannel is used as a default CNI.

2021-04-09 14:42 UTC, mrostecki requested changes
In general looks good, thanks for working on that feature!

I left some nit comments, mostly about wrapping errors with `%w`.

2021-04-09 14:42 UTC, mrostecki commented on backend/vxlan/device.go
> +		return fmt.Errorf("failed to ensure v6 address of interface %s: %s", dev.link.Attrs().Name, err)
```suggestion
		return fmt.Errorf("failed to ensure v6 address of interface %s: %w", dev.link.Attrs().Name, err)
```

2021-04-09 14:42 UTC, mrostecki commented on backend/vxlan/device.go
> +		return fmt.Errorf("failed to set v6 interface %s to UP state: %s", dev.link.Attrs().Name, err)
```suggestion
		return fmt.Errorf("failed to set v6 interface %s to UP state: %w", dev.link.Attrs().Name, err)
```

2021-04-09 14:42 UTC, mrostecki commented on backend/vxlan/vxlan.go
> +			return nil, fmt.Errorf("failed to configure interface %s: %s", dev.link.Attrs().Name, err)
```suggestion
			return nil, fmt.Errorf("failed to configure interface %s: %w", dev.link.Attrs().Name, err)
```

2021-04-09 14:42 UTC, mrostecki commented on backend/vxlan/vxlan.go
> +			return nil, fmt.Errorf("failed to configure interface %s: %s", v6Dev.link.Attrs().Name, err)
```suggestion
			return nil, fmt.Errorf("failed to configure interface %s: %w", v6Dev.link.Attrs().Name, err)
```

2021-04-09 14:42 UTC, mrostecki commented on pkg/ip/iface.go
> +					return fmt.Errorf("failed to remove v6 IP address %s from %s: %s", ipn.String(), link.Attrs().Name, err)
```suggestion
					return fmt.Errorf("failed to remove v6 IP address %s from %s: %w", ipn.String(), link.Attrs().Name, err)
```

2021-04-09 14:42 UTC, mrostecki commented on pkg/ip/iface.go
> +			return fmt.Errorf("failed to add v6 IP address %s to %s: %s", ipn.String(), link.Attrs().Name, err)
```suggestion
			return fmt.Errorf("failed to add v6 IP address %s to %s: %w", ipn.String(), link.Attrs().Name, err)
```

2021-04-09 14:42 UTC, mrostecki commented on subnet/config_test.go
> +	if cfg.IPv6SubnetMin.String() != "fc00:0:0:1::" {
nit: maybe store `"fc00:0:0:1::"` in a variable (i.e. `expectedSubnetMit`), similar to `expectedNet` above?

2021-04-21 19:09 UTC, narqo commented on backend/vxlan/vxlan_network.go
> +			log.Warningf("ignoring non-vxlan v4Subnet(%s) v6Subnet: type=%v", sn, v6Sn, attrs.BackendType)
Seems like a typo

```suggestion
			log.Warningf("ignoring non-vxlan v4Subnet(%s) v6Subnet(%s): type=%v", sn, v6Sn, attrs.BackendType)
```

2021-05-28 13:06 UTC, manuelbuil commented
Due to the unresponsiveness of the author, this PR https://github.com/flannel-io/flannel/pull/1446 supersedes this one

2021-07-22 15:39 UTC, manuelbuil commented
We can close this one as https://github.com/flannel-io/flannel/pull/1448 was merged

2021-07-22 15:39 UTC, closed without merging