Fixed masquerade rule to avoid double NAT bug
flannel-io/flannel pull request #1681
Opened 2022-11-23 13:23 UTC by rbrtbnfgl

## Description

Added iptables rule that check marked packed by Kube-proxy to avoid double-NAT that could slow down the connection or in some kernel versions loss packets.

Issue: #1679

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Release note

## Release Note

```release-note
None required
```

2022-11-23 13:31 UTC, thomasferrandiz requested changes

2022-11-23 13:31 UTC, thomasferrandiz commented on network/iptables_test.go
>  		t.Errorf("Should be 5 masqRules, there are actually %d: %#v", len(ipt.rules), ipt.rules)
small note: the error message should be come:
`Should be 6 masqRules`

2022-11-23 17:35 UTC, manuelbuil approved these changes

2022-11-25 09:29 UTC, thomasferrandiz approved these changes

2022-11-29 14:41 UTC, merged